steps:
- name: 'gcr.io/cloud-builders/wget'
  args:
  - '--quiet'
  - '-O'
  - 'pnpm'
  - 'https://get.pnpm.io/install.sh'

- name: 'debian:11'
  args:
  - 'bash'
  - '-c'
  - |
    mv pnpm /tmp
    chmod 755 /tmp/pnpm
    /tmp/pnpm install"

- name: 'node:lts'
  args:
    - '/tmp/pnpm run build'
  id: 'Build the application'

- name: 'gcr.io/cloud-builders/wget'
  args:
  - '--quiet'
  - '-O'
  - 'firebase'
  - 'https://firebase.tools/bin/linux/latest'
  
- name: 'debian:11'
  args:
  - 'bash'
  - '-c'
  - |
    mv firebase /tmp
    chmod 755 /tmp/firebase
    /tmp/firebase deploy --project ${PROJECT_ID} --non-interactive -m "Build ${BUILD_ID}"